name: Build Lib
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - run: npm install
    - run: yarn build
    - run: yarn build-storybook